# Compute contribution decay from PostgreSQL, inspect it, then write to PostgreSQL

This notebook deliberately separates algorithm computation from database writes:

1. Compute decay results and save bounded Parquet parts.
2. Inspect and manually verify those results.
3. Run a separate explicit cell to replace and write the verified results to the configured PostgreSQL score schema.

In [31]:
# Configuration
from datetime import datetime, timezone
from pathlib import Path

from mindshare_config import pg_score_schema

SCOPE = "project"  # "project" or "global"
PROJECT_KEYWORD = "quipnetwork"  # only used for project scope
SOURCE_TARGET = "pg"
DESTINATION_SCHEMA = pg_score_schema()
WRITE_METHOD = "copy"  # fastest PostgreSQL benchmark; alternative: "multirow"
SOURCE_BATCH_SIZE = 100_000
WRITE_BATCH_SIZE = 100_000
INCLUDE_ACTIVE_MULTIPLIERS = False

RUN_ID = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
OUTPUT_DIR = Path("output") / f"{SCOPE}_{PROJECT_KEYWORD}_{RUN_ID}"

assert SCOPE in {"project", "global"}
assert SOURCE_TARGET == "pg"
assert DESTINATION_SCHEMA != "mindshare"
if SCOPE == "project":
    assert PROJECT_KEYWORD

print("Computed results will be stored in:", OUTPUT_DIR)

Computed results will be stored in: output/project_quipnetwork_20260615T061427Z

In [32]:
# Imports
from importlib import reload
from inspect import getsource
from time import perf_counter

import polars as pl
import mindshare_compute.db as db_module

# Reload because Jupyter caches imported modules between runs.
reload(db_module)

from mindshare_compute.decay import DecayComputer

iter_decay_source = db_module.iter_decay_source
DecayResultWriter = db_module.DecayResultWriter

pl.Config.set_tbl_rows(20)
assert "destination schema must not be the read-only source schema" in getsource(DecayResultWriter.__init__)
assert "with cursor.copy(copy_statement) as copy" in getsource(DecayResultWriter._write_batch_copy)
print("Loaded PostgreSQL-safe writer from:", db_module.__file__)

Loaded PostgreSQL-safe writer from: /home/babin411/Nucleus/mindshare-backend-optimization/mindshare_compute/db.py

## 1. Compute algorithm results only

This cell reads only from PostgreSQL `mindshare`. It **does not write to any database**. Each computed batch is saved as a Parquet part so the complete result can be inspected without holding it all in WSL memory.

In [33]:
computer = DecayComputer(
    SCOPE,
    include_active_multipliers=INCLUDE_ACTIVE_MULTIPLIERS,
)
source = iter_decay_source(
    SCOPE,
    PROJECT_KEYWORD if SCOPE == "project" else None,
    target=SOURCE_TARGET,
    batch_size=SOURCE_BATCH_SIZE,
)

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
compute_start = perf_counter()
compute_seconds = 0.0
rows_computed = 0
parts_written = 0
last_computed_batch = None

for batch_number, source_batch in enumerate(source):
    started = perf_counter()
    result_batch = computer.process_batch(source_batch)
    compute_seconds += perf_counter() - started

    result_batch.write_parquet(OUTPUT_DIR / f"part-{batch_number:05d}.parquet")
    rows_computed += result_batch.height
    parts_written += 1
    last_computed_batch = result_batch
    print(f"computed part={batch_number:05d} total_rows={rows_computed:,}")

compute_summary = pl.DataFrame({
    "source_target": [SOURCE_TARGET],
    "source_schema": [db_module.source_schema(SOURCE_TARGET)],
    "scope": [SCOPE],
    "project_keyword": [PROJECT_KEYWORD if SCOPE == "project" else None],
    "rows_computed": [rows_computed],
    "parquet_parts": [parts_written],
    "algorithm_compute_seconds": [compute_seconds],
    "compute_and_parquet_wall_seconds": [perf_counter() - compute_start],
})
compute_summary

computed part=00000 total_rows=100,000
computed part=00001 total_rows=200,000
computed part=00002 total_rows=300,000
computed part=00003 total_rows=400,000
computed part=00004 total_rows=500,000
computed part=00005 total_rows=600,000
computed part=00006 total_rows=700,000
computed part=00007 total_rows=800,000
computed part=00008 total_rows=900,000
computed part=00009 total_rows=1,000,000
computed part=00010 total_rows=1,100,000
computed part=00011 total_rows=1,200,000
computed part=00012 total_rows=1,300,000
computed part=00013 total_rows=1,400,000
computed part=00014 total_rows=1,500,000
computed part=00015 total_rows=1,600,000
computed part=00016 total_rows=1,700,000
computed part=00017 total_rows=1,800,000
computed part=00018 total_rows=1,900,000
computed part=00019 total_rows=2,000,000
computed part=00020 total_rows=2,100,000
computed part=00021 total_rows=2,200,000
computed part=00022 total_rows=2,300,000
computed part=00023 total_rows=2,400,000
computed part=00024 total_rows=2,450,876

shape: (1, 8)
┌────────────┬────────────┬─────────┬────────────┬────────────┬────────────┬───────────┬───────────┐
│ source_tar ┆ source_sch ┆ scope   ┆ project_ke ┆ rows_compu ┆ parquet_pa ┆ algorithm ┆ compute_a │
│ get        ┆ ema        ┆ ---     ┆ yword      ┆ ted        ┆ rts        ┆ _compute_ ┆ nd_parque │
│ ---        ┆ ---        ┆ str     ┆ ---        ┆ ---        ┆ ---        ┆ seconds   ┆ t_wall_se │
│ str        ┆ str        ┆         ┆ str        ┆ i64        ┆ i64        ┆ ---       ┆ con…      │
│            ┆            ┆         ┆            ┆            ┆            ┆ f64       ┆ ---       │
│            ┆            ┆         ┆            ┆            ┆            ┆           ┆ f64       │
╞════════════╪════════════╪═════════╪════════════╪════════════╪════════════╪═══════════╪═══════════╡
│ pg         ┆ mindshare  ┆ project ┆ quipnetwor ┆ 2450876    ┆ 25         ┆ 24.343458 ┆ 383.11891 │
│            ┆            ┆         ┆ k          ┆            ┆            ┆           ┆           │
└────────────┴────────────┴─────────┴────────────┴────────────┴────────────┴───────────┴───────────┘

## 2. Manually inspect and verify

These cells scan the saved Parquet files lazily. Nothing is written to PostgreSQL here. Add any manual checks you need before running the database-write section.

In [34]:
result_scan = pl.scan_parquet(OUTPUT_DIR / "*.parquet")

result_scan.head(50).collect()

shape: (50, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ project_k ┆ reply_pos ┆ original_ ┆ replier_x ┆ … ┆ contribut ┆ reply_num ┆ local_rep ┆ decay_ty │
│ eyword    ┆ t_id      ┆ post_id   ┆ _id       ┆   ┆ ion_score ┆ ber       ┆ ly_count  ┆ pe       │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ f64       ┆ i64       ┆ i64       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ quipnetwo ┆ 204421085 ┆ 204420235 ┆           ┆ … ┆ 0.0       ┆ 1         ┆ 1         ┆ FIRST_RE │
│ rk        ┆ 646106251 ┆ 429190457 ┆           ┆   ┆           ┆           ┆           ┆ PLY      │
│           ┆ 2         ┆ 5         ┆           ┆   ┆           ┆           ┆           ┆          │
│ quipnetwo ┆ 204421124 ┆ 204336573 ┆           ┆ … ┆ 0.0       ┆ 2         ┆ 1         ┆ GLOBAL_D │
│ rk        ┆ 201371284 ┆ 061230187 ┆           ┆   ┆           ┆           ┆           ┆ ECAY     │
│           ┆ 0         ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆          │
│ quipnetwo ┆ 204421209 ┆ 204421050 ┆           ┆ … ┆ 0.0       ┆ 3         ┆ 1         ┆ GLOBAL_D │
│ rk        ┆ 335284989 ┆ 577942553 ┆           ┆   ┆           ┆           ┆           ┆ ECAY     │
│           ┆ 4         ┆ 4         ┆           ┆   ┆           ┆           ┆           ┆          │
│ quipnetwo ┆ 204421245 ┆ 204421231 ┆           ┆ … ┆ 0.0       ┆ 4         ┆ 1         ┆ GLOBAL_D │
│ rk        ┆ 459147583 ┆ 560062986 ┆           ┆   ┆           ┆           ┆           ┆ ECAY     │
│           ┆ 3         ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆          │
│ quipnetwo ┆ 204421253 ┆ 204278341 ┆           ┆ … ┆ 0.0       ┆ 5         ┆ 1         ┆ GLOBAL_D │
│ rk        ┆ 833472455 ┆ 288555758 ┆           ┆   ┆           ┆           ┆           ┆ ECAY     │
│           ┆ 7         ┆ 4         ┆           ┆   ┆           ┆           ┆           ┆          │
│ quipnetwo ┆ 204421258 ┆ 204275777 ┆           ┆ … ┆ 0.0       ┆ 6         ┆ 1         ┆ GLOBAL_D │
│ rk        ┆ 122560730 ┆ 737920147 ┆           ┆   ┆           ┆           ┆           ┆ ECAY     │
│           ┆ 5         ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆          │
│ quipnetwo ┆ 204421982 ┆ 204421907 ┆           ┆ … ┆ 0.0       ┆ 7         ┆ 1         ┆ GLOBAL_D │
│ rk        ┆ 970882895 ┆ 704517032 ┆           ┆   ┆           ┆           ┆           ┆ ECAY     │
│           ┆ 6         ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆          │
│ quipnetwo ┆ 204421982 ┆ 204421382 ┆           ┆ … ┆ 0.0       ┆ 8         ┆ 1         ┆ GLOBAL_D │
│ rk        ┆ 964172023 ┆ 483703816 ┆           ┆   ┆           ┆           ┆           ┆ ECAY     │
│           ┆ 7         ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆          │
│ quipnetwo ┆ 204422005 ┆ 204421907 ┆           ┆ … ┆ 0.0       ┆ 9         ┆ 2         ┆ LOCAL_DE │
│ rk        ┆ 995940286 ┆ 704517032 ┆           ┆   ┆           ┆           ┆           ┆ CAY      │
│           ┆ 1         ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆          │
│ quipnetwo ┆ 204422055 ┆ 204255777 ┆           ┆ … ┆ 0.0       ┆ 10        ┆ 1         ┆ GLOBAL_D │
│ rk        ┆ 064257758 ┆ 190882121 ┆           ┆   ┆           ┆           ┆           ┆ ECAY     │
│           ┆ 3         ┆ 6         ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ quipnetwo ┆ 204424857 ┆ 204424441 ┆           ┆ … ┆ 0.0       ┆ 41        ┆ 1         ┆ GLOBAL_D │
│ rk        ┆ 618086750 ┆ 656368768 ┆           ┆   ┆           ┆           ┆           ┆ ECAY     │
│           ┆ 8         ┆ 4         ┆           ┆   ┆           ┆           ┆           ┆          │
│ quipnetwo ┆ 204425271 ┆ 204423338 ┆           ┆ … ┆ 0.0       ┆ 42        ┆ 2         ┆ LOCAL_DE │
│ rk        ┆ 920942727 ┆ 737707845 ┆           ┆   ┆           ┆           ┆           ┆ CAY      │
│           ┆ 5         ┆ 6         ┆           ┆   ┆           ┆           ┆           ┆          │
│ quipnetwo ┆ 204425282 ┆ 204424256 ┆           ┆ … ┆ 0.0       ┆ 43        ┆ 1         ┆ GLOBAL_D │
│ rk        ┆ 790900963 ┆ 092810052 ┆           ┆   ┆           ┆           ┆           ┆ ECAY     │
│           ┆ 5         ┆ 2         ┆           ┆   ┆           ┆           ┆           ┆          │
│ quipnetwo ┆ 204425288 ┆ 204424936 ┆           ┆ … ┆ 0.0       ┆ 44        ┆ 1         ┆ GLOBAL_D │
│ rk        ┆ 352104474 ┆ 324584696 ┆           ┆   ┆           ┆           ┆           ┆ ECAY     │
│           ┆ 5         ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆          │
│ quipnetwo ┆ 204425383 ┆ 204425235 ┆           ┆ … ┆ 0.0       ┆ 45        ┆ 1         ┆ GLOBAL_D │
│ rk        ┆ 190349427 ┆ 302121924 ┆           ┆   ┆           ┆           ┆           ┆ ECAY     │
│           ┆ 7         ┆ 7         ┆           ┆   ┆           ┆           ┆           ┆          │
│ quipnetwo ┆ 204425383 ┆ 204425360 ┆           ┆ … ┆ 0.0       ┆ 46        ┆ 1         ┆ GLOBAL_D │
│ rk        ┆ 664332418 ┆ 661513461 ┆           ┆   ┆           ┆           ┆           ┆ ECAY     │
│           ┆ 3         ┆ 3         ┆           ┆   ┆           ┆           ┆           ┆          │
│ quipnetwo ┆ 204425386 ┆ 204425321 ┆           ┆ … ┆ 0.0       ┆ 47        ┆ 1         ┆ GLOBAL_D │
│ rk        ┆ 486237232 ┆ 624256109 ┆           ┆   ┆           ┆           ┆           ┆ ECAY     │
│           ┆ 9         ┆ 3         ┆           ┆   ┆           ┆           ┆           ┆          │
│ quipnetwo ┆ 204425394 ┆ 204425322 ┆           ┆ … ┆ 0.0       ┆ 48        ┆ 1         ┆ GLOBAL_D │
│ rk        ┆ 129120089 ┆ 515999168 ┆           ┆   ┆           ┆           ┆           ┆ ECAY     │
│           ┆ 8         ┆ 3         ┆           ┆   ┆           ┆           ┆           ┆          │
│ quipnetwo ┆ 204425409 ┆ 204421907 ┆           ┆ … ┆ 0.0       ┆ 49        ┆ 6         ┆ LOCAL_DE │
│ rk        ┆ 664399398 ┆ 704517032 ┆           ┆   ┆           ┆           ┆           ┆ CAY      │
│           ┆ 6         ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆          │
│ quipnetwo ┆ 204425424 ┆ 204424936 ┆           ┆ … ┆ 0.0       ┆ 50        ┆ 2         ┆ LOCAL_DE │
│ rk        ┆ 439262838 ┆ 324584696 ┆           ┆   ┆           ┆           ┆           ┆ CAY      │
│           ┆ 5         ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [35]:
# Useful high-level verification before writing.
result_scan.group_by("decay_type").agg(
    pl.len().alias("rows"),
    pl.col("contribution_score").min().alias("min_score"),
    pl.col("contribution_score").mean().alias("mean_score"),
    pl.col("contribution_score").max().alias("max_score"),
).sort("decay_type").collect()

shape: (3, 5)
┌──────────────┬─────────┬───────────┬────────────┬───────────┐
│ decay_type   ┆ rows    ┆ min_score ┆ mean_score ┆ max_score │
│ ---          ┆ ---     ┆ ---       ┆ ---        ┆ ---       │
│ str          ┆ u32     ┆ f64       ┆ f64        ┆ f64       │
╞══════════════╪═════════╪═══════════╪════════════╪═══════════╡
│ FIRST_REPLY  ┆ 41495   ┆ 0.0       ┆ 75.088747  ┆ 2645.09   │
│ GLOBAL_DECAY ┆ 575436  ┆ 0.0       ┆ 14.041813  ┆ 2372.19   │
│ LOCAL_DECAY  ┆ 1833945 ┆ 0.0       ┆ 2.84168    ┆ 1019.65   │
└──────────────┴─────────┴───────────┴────────────┴───────────┘

In [36]:
# Change these filters for a replier or author you want to verify manually.
VERIFY_REPLIER_X_ID = None
VERIFY_ORIGINAL_AUTHOR_X_ID = None

verification = result_scan
if VERIFY_REPLIER_X_ID:
    verification = verification.filter(pl.col("replier_x_id") == VERIFY_REPLIER_X_ID)
if VERIFY_ORIGINAL_AUTHOR_X_ID:
    verification = verification.filter(
        pl.col("original_author_x_id") == VERIFY_ORIGINAL_AUTHOR_X_ID
    )

verification.sort("replier_x_id", "post_created_at").head(200).collect()

shape: (200, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ project_k ┆ reply_pos ┆ original_ ┆ replier_x ┆ … ┆ contribut ┆ reply_num ┆ local_rep ┆ decay_ty │
│ eyword    ┆ t_id      ┆ post_id   ┆ _id       ┆   ┆ ion_score ┆ ber       ┆ ly_count  ┆ pe       │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ f64       ┆ i64       ┆ i64       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ quipnetwo ┆ 204421085 ┆ 204420235 ┆           ┆ … ┆ 0.0       ┆ 1         ┆ 1         ┆ FIRST_RE │
│ rk        ┆ 646106251 ┆ 429190457 ┆           ┆   ┆           ┆           ┆           ┆ PLY      │
│           ┆ 2         ┆ 5         ┆           ┆   ┆           ┆           ┆           ┆          │
│ quipnetwo ┆ 204421124 ┆ 204336573 ┆           ┆ … ┆ 0.0       ┆ 2         ┆ 1         ┆ GLOBAL_D │
│ rk        ┆ 201371284 ┆ 061230187 ┆           ┆   ┆           ┆           ┆           ┆ ECAY     │
│           ┆ 0         ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆          │
│ quipnetwo ┆ 204421209 ┆ 204421050 ┆           ┆ … ┆ 0.0       ┆ 3         ┆ 1         ┆ GLOBAL_D │
│ rk        ┆ 335284989 ┆ 577942553 ┆           ┆   ┆           ┆           ┆           ┆ ECAY     │
│           ┆ 4         ┆ 4         ┆           ┆   ┆           ┆           ┆           ┆          │
│ quipnetwo ┆ 204421245 ┆ 204421231 ┆           ┆ … ┆ 0.0       ┆ 4         ┆ 1         ┆ GLOBAL_D │
│ rk        ┆ 459147583 ┆ 560062986 ┆           ┆   ┆           ┆           ┆           ┆ ECAY     │
│           ┆ 3         ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆          │
│ quipnetwo ┆ 204421253 ┆ 204278341 ┆           ┆ … ┆ 0.0       ┆ 5         ┆ 1         ┆ GLOBAL_D │
│ rk        ┆ 833472455 ┆ 288555758 ┆           ┆   ┆           ┆           ┆           ┆ ECAY     │
│           ┆ 7         ┆ 4         ┆           ┆   ┆           ┆           ┆           ┆          │
│ quipnetwo ┆ 204421258 ┆ 204275777 ┆           ┆ … ┆ 0.0       ┆ 6         ┆ 1         ┆ GLOBAL_D │
│ rk        ┆ 122560730 ┆ 737920147 ┆           ┆   ┆           ┆           ┆           ┆ ECAY     │
│           ┆ 5         ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆          │
│ quipnetwo ┆ 204421982 ┆ 204421907 ┆           ┆ … ┆ 0.0       ┆ 7         ┆ 1         ┆ GLOBAL_D │
│ rk        ┆ 970882895 ┆ 704517032 ┆           ┆   ┆           ┆           ┆           ┆ ECAY     │
│           ┆ 6         ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆          │
│ quipnetwo ┆ 204421982 ┆ 204421382 ┆           ┆ … ┆ 0.0       ┆ 8         ┆ 1         ┆ GLOBAL_D │
│ rk        ┆ 964172023 ┆ 483703816 ┆           ┆   ┆           ┆           ┆           ┆ ECAY     │
│           ┆ 7         ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆          │
│ quipnetwo ┆ 204422005 ┆ 204421907 ┆           ┆ … ┆ 0.0       ┆ 9         ┆ 2         ┆ LOCAL_DE │
│ rk        ┆ 995940286 ┆ 704517032 ┆           ┆   ┆           ┆           ┆           ┆ CAY      │
│           ┆ 1         ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆          │
│ quipnetwo ┆ 204422055 ┆ 204255777 ┆           ┆ … ┆ 0.0       ┆ 10        ┆ 1         ┆ GLOBAL_D │
│ rk        ┆ 064257758 ┆ 190882121 ┆           ┆   ┆           ┆           ┆           ┆ ECAY     │
│           ┆ 3         ┆ 6         ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ quipnetwo ┆ 204647184 ┆ 204644637 ┆           ┆ … ┆ 0.0       ┆ 191       ┆ 13        ┆ LOCAL_DE │
│ rk        ┆ 395188668 ┆ 411637669 ┆           ┆   ┆           ┆           ┆           ┆ CAY      │
│           ┆ 8         ┆ 2         ┆           ┆   ┆           ┆           ┆           ┆          │
│ quipnetwo ┆ 204647262 ┆ 204644637 ┆           ┆ … ┆ 0.0       ┆ 192       ┆ 14        ┆ LOCAL_DE │
│ rk        ┆ 308577697 ┆ 411637669 ┆           ┆   ┆           ┆           ┆           ┆ CAY      │
│           ┆ 9         ┆ 2         ┆           ┆   ┆           ┆           ┆           ┆          │
│ quipnetwo ┆ 204648846 ┆ 204644637 ┆           ┆ … ┆ 0.0       ┆ 193       ┆ 15        ┆ LOCAL_DE │
│ rk        ┆ 230025444 ┆ 411637669 ┆           ┆   ┆           ┆           ┆           ┆ CAY      │
│           ┆ 9         ┆ 2         ┆           ┆   ┆           ┆           ┆           ┆          │
│ quipnetwo ┆ 204648938 ┆ 204644637 ┆           ┆ … ┆ 0.0       ┆ 194       ┆ 16        ┆ LOCAL_DE │
│ rk        ┆ 001815148 ┆ 411637669 ┆           ┆   ┆           ┆           ┆           ┆ CAY      │
│           ┆ 8         ┆ 2         ┆           ┆   ┆           ┆           ┆           ┆          │
│ quipnetwo ┆ 204668598 ┆ 204644637 ┆           ┆ … ┆ 0.0       ┆ 195       ┆ 17        ┆ LOCAL_DE │
│ rk        ┆ 705337170 ┆ 411637669 ┆           ┆   ┆           ┆           ┆           ┆ CAY      │
│           ┆ 2         ┆ 2         ┆           ┆   ┆           ┆           ┆           ┆          │
│ quipnetwo ┆ 204937637 ┆ 204937495 ┆           ┆ … ┆ 0.0       ┆ 196       ┆ 1         ┆ GLOBAL_D │
│ rk        ┆ 348819375 ┆ 068800661 ┆           ┆   ┆           ┆           ┆           ┆ ECAY     │
│           ┆ 6         ┆ 3         ┆           ┆   ┆           ┆           ┆           ┆          │
│ quipnetwo ┆ 204937655 ┆ 204937495 ┆           ┆ … ┆ 0.0       ┆ 197       ┆ 2         ┆ LOCAL_DE │
│ rk        ┆ 486248596 ┆ 068800661 ┆           ┆   ┆           ┆           ┆           ┆ CAY      │
│           ┆ 6         ┆ 3         ┆           ┆   ┆           ┆           ┆           ┆          │
│ quipnetwo ┆ 204937656 ┆ 204937495 ┆           ┆ … ┆ 0.0       ┆ 198       ┆ 3         ┆ LOCAL_DE │
│ rk        ┆ 251734446 ┆ 068800661 ┆           ┆   ┆           ┆           ┆           ┆ CAY      │
│           ┆ 8         ┆ 3         ┆           ┆   ┆           ┆           ┆           ┆          │
│ quipnetwo ┆ 204937821 ┆ 204937495 ┆           ┆ … ┆ 0.0       ┆ 199       ┆ 4         ┆ LOCAL_DE │
│ rk        ┆ 587842669 ┆ 068800661 ┆           ┆   ┆           ┆           ┆           ┆ CAY      │
│           ┆ 6         ┆ 3         ┆           ┆   ┆           ┆           ┆           ┆          │
│ quipnetwo ┆ 204937864 ┆ 204937495 ┆           ┆ … ┆ 0.0       ┆ 200       ┆ 5         ┆ LOCAL_DE │
│ rk        ┆ 542094569 ┆ 068800661 ┆           ┆   ┆           ┆           ┆           ┆ CAY      │
│           ┆ 2         ┆ 3         ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## 3. Write verified Parquet results to PostgreSQL

Run this cell only after manually verifying the algorithm output. It writes only to the configured PostgreSQL score schema; the source `mindshare` schema remains read-only.

- Project scope deletes that project's existing rows from the configured score schema's `test_contribution_scores` table before writing.
- Global scope truncates the configured score schema's `test_global_contribution_scores` table before writing.
- The writer creates the schema/table when they do not exist.

In [37]:
# Explicit safety switch: change to True only after inspecting the results above.
WRITE_VERIFIED_RESULTS_TO_POSTGRES = True

if not WRITE_VERIFIED_RESULTS_TO_POSTGRES:
    raise RuntimeError(
        "Set WRITE_VERIFIED_RESULTS_TO_POSTGRES = True after manually verifying the Parquet results."
    )

write_start = perf_counter()
write_seconds = 0.0
rows_written = 0

# collect_batches streams the verified Parquet dataset without loading it all.
parquet_batches = pl.scan_parquet(OUTPUT_DIR / "*.parquet").collect_batches(
    chunk_size=WRITE_BATCH_SIZE,
    maintain_order=True,
)

with DecayResultWriter(
    SCOPE,
    PROJECT_KEYWORD if SCOPE == "project" else None,
    target="pg",
    destination_schema=DESTINATION_SCHEMA,
    write_method=WRITE_METHOD,
) as writer:
    for batch_number, result_batch in enumerate(parquet_batches):
        started = perf_counter()
        rows_written += writer.write_batch(result_batch)
        write_seconds += perf_counter() - started
        print(f"wrote batch={batch_number:05d} total_rows={rows_written:,}")

write_summary = pl.DataFrame({
    "write_target": ["pg"],
    "destination_schema": [DESTINATION_SCHEMA],
    "write_method": [WRITE_METHOD],
    "rows_written": [rows_written],
    "postgres_write_seconds": [write_seconds],
    "write_wall_seconds": [perf_counter() - write_start],
})
write_summary

wrote batch=00000 total_rows=100,000
wrote batch=00001 total_rows=200,000
wrote batch=00002 total_rows=300,000
wrote batch=00003 total_rows=400,000
wrote batch=00004 total_rows=500,000
wrote batch=00005 total_rows=600,000
wrote batch=00006 total_rows=700,000
wrote batch=00007 total_rows=800,000
wrote batch=00008 total_rows=900,000
wrote batch=00009 total_rows=1,000,000
wrote batch=00010 total_rows=1,100,000
wrote batch=00011 total_rows=1,200,000
wrote batch=00012 total_rows=1,300,000
wrote batch=00013 total_rows=1,400,000
wrote batch=00014 total_rows=1,500,000
wrote batch=00015 total_rows=1,600,000
wrote batch=00016 total_rows=1,700,000
wrote batch=00017 total_rows=1,800,000
wrote batch=00018 total_rows=1,900,000
wrote batch=00019 total_rows=2,000,000
wrote batch=00020 total_rows=2,100,000
wrote batch=00021 total_rows=2,200,000
wrote batch=00022 total_rows=2,300,000
wrote batch=00023 total_rows=2,400,000
wrote batch=00024 total_rows=2,450,876

shape: (1, 6)
┌──────────────┬─────────────────┬──────────────┬──────────────┬─────────────────┬─────────────────┐
│ write_target ┆ destination_sch ┆ write_method ┆ rows_written ┆ postgres_write_ ┆ write_wall_seco │
│ ---          ┆ ema             ┆ ---          ┆ ---          ┆ seconds         ┆ nds             │
│ str          ┆ ---             ┆ str          ┆ i64          ┆ ---             ┆ ---             │
│              ┆ str             ┆              ┆              ┆ f64             ┆ f64             │
╞══════════════╪═════════════════╪══════════════╪══════════════╪═════════════════╪═════════════════╡
│ pg           ┆ mindshare_score ┆ copy         ┆ 2450876      ┆ 103.54214       ┆ 110.141701      │
│              ┆ _test           ┆              ┆              ┆                 ┆                 │
└──────────────┴─────────────────┴──────────────┴──────────────┴─────────────────┴─────────────────┘